### PR TITLE
[Merged by Bors] - snap: migrate to `base: core22`

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
Looking good!

**Review by AlanGriffiths — APPROVED** [review]
Still looking good

**Review by AlanGriffiths — APPROVED** [review]
Ok, good catch. I hadn't noticed that `mir-quirks` had moved for core22 (was there a reason?)

**Comment by Saviq** [comment]
> Ok, good catch. I hadn't noticed that `mir-quirks` had moved for core22 (was there a reason?)

Just wanted for all things that are part of the interface to be top level in the content shared. Avoids mistaken assumptions and need to be explicitly placed.

**Review by AlanGriffiths — APPROVED** [review]
bors merge

**Review by AlanGriffiths — APPROVED** [review]
bors merge

**Pull request closed without merging**
