### PR TITLE
Switch to LZO compression for faster startup

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by ogra1** [comment]
I just did some testing on a Raspberry Pi4 where i re-implemented the splash screen into the boot process ... with the old xz compression ubuntu frame takes about 5-6 seconds to start after the splash is gone from the screen (manually stopwatched), testing with lzo compression got that down to 2-3sec, the difference is significantly noticeable on boot ...

**Comment by AlanGriffiths** [comment]
There's also https://github.com/MirServer/mesa-core20/pull/6

**Review by wmww — CHANGES_REQUESTED** [review]
Looks like ` .idea/` got added before it was put in .gitignore, and needs to be dropped.

Other than that, sounds like a good idea to me.

**Comment by AlanGriffiths** [comment]
> Other than that, sounds like a good idea to me.

Close enough to approval:

bors r=@wmww

**Pull request merged**
