### PR TITLE
Add eglstream-kms

### PR DESCRIPTION
**Pull request by AlanGriffiths**
For testing with Nvidia

### CODE REVIEW

**Review by xnox — APPROVED** [review]

**Comment by xnox** [comment]
I guess this is also in some ways a duplicate of https://github.com/MirServer/ubuntu-frame/pull/44 cause that one would also cause the eglstream platform to be available.

**Comment by AlanGriffiths** [comment]
@xnox we're not going to land this given the current state of Nvidia support on Core.

But there is a corresponding release in the store: `edge/pr43`.

**Comment by xnox** [comment]
> @xnox we're not going to land this given the current state of Nvidia support on Core.
> 
> But there is a corresponding release in the store: `edge/pr43`.

surely it is mostly harmless to land this ;-)

**Comment by AlanGriffiths** [comment]
> surely it is mostly harmless to land this ;-)

You know some folks don't need much reason to think something works before they complain that it doesn't.

**Comment by Saviq** [comment]
This got added through #117

**Pull request closed without merging**
